version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mern-server
    restart: always
    ports:
      - '80:3005'
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo:7
    container_name: mern-mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      - MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
